### ISSUE TITLE
Why do you approach your data using the size (4, 1, DATASIZE)?

### ISSUE THREAD

**Issue by vmesel** [gifford-lab/Keras-genomics#1]
Why do you approach your data using the size (4, 1, DATASIZE)?
https://github.com/gifford-lab/Keras-genomics/blob/master/example/model.py#L32

**Comment by haoyangz** [comment]
As is the common [practice](http://www.nature.com/nbt/journal/v33/n8/full/nbt.3300.html) in genomics, DNA sequences are converted to 4xDATASIZE matrix, where each column is an one-hot encoding of a nucleotide. The [example model](https://github.com/gifford-lab/Keras-genomics/blob/master/example/model.py) uses "Convolutional2D" layer which takes images of dimension (n_sample, n_channel, n_weight, n_height), so we instead embed a DNA sequence to 4X1XDATASIZE using the provided [helper file](https://github.com/gifford-lab/Keras-genomics/blob/master/embedH5.py). But you are free to use your own ways of encoding DNA sequences and other Keras layers, for instance "Convolution1D",  that take input of different shape.

**Comment by vmesel** [comment]
If I used some kmers for my DL approach, how would I do the Convolution1D?

I'm with a dataset with 65516 columns and 1200 rows of lincRNAs related to Prostate Cancer and I don't know how to proceed on the implementation.

**Comment by haoyangz** [comment]
I assume each of your 65516 (or maybe 65536?) columns represents one possible kmer? I don't see a sensible way to use convolutional neural network on this set of features, as the index of the feature is not important and inter-changable. If I were you, I might start with regular neural networks (fully connected)  which correspond to "[Dense](https://keras.io/layers/core/#dense)" layer in Keras. The first layer would have 65516 nodes, one correspond to one k-mer, and the next few layers have however many you want. For detailed example of implementing different network structures with Keras, please refer to its [official website](https://keras.io/).  If you are not familiar with Keras, I would suggest you forget about my software and directly implement a Keras model. Once you have a runnable Keras model ready, you can use this software to automate training, hyper-parameter tuning and testing.

**Comment by vmesel** [comment]
Thanks for the help!
