### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by shay86** [gifford-lab/Keras-genomics#2]
Hi, 
I am trying to run your code without Docker under CPU, but i get this error that i don't understand :+1: 
can any one help me ...thanks

    Using Theano backend.
    Traceback (most recent call last):
    File "main.py", line 50, in <module>
    model_arch = basename(args.model)
    File "/usr/lib/python2.7/posixpath.py", line 114, in basename
    i = p.rfind('/') + 1
   AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by haoyangz** [comment]
Did you feed in a model file argument (-m, or --model) ?

**Comment by shay86** [comment]
No i did not add any model argument.... is it required? 
MODEL_TOPDIR: the absolute path of the model file directory 
Is this the data file that i produced from the first program and put it in $REPO_HOME/expt1 ??
sorry to bother you but i try to understand

**Comment by haoyangz** [comment]
In the **Model preparation** section, you should prepare a model file.  Then when running the main program, use the path to that file as the argument to `MODEL_FILE_NAME`

**Comment by shay86** [comment]
sorry to bother you but i am trying me best but i dont get how to set the arguments in 

python $REPO_HOME/main.py -d DATA_TOPDIR -c DATA_CODE -m MODEL_TOPDIR/MODEL_FILE_NAME -s SEQ_SIZE ORDER

I try to add example of toy data as the -m argument and i get this error:
 

    python main.py -m /media/shayan/VolumE/Keras-genomics-master/example
    Using Theano backend.
    Traceback (most recent call last):
     File "main.py", line 54, in <module>
     outdir = join(topdir,model_arch)
     File "/usr/lib/python2.7/posixpath.py", line 70, in join
      elif path == '' or path.endswith('/'):
     AttributeError: 'NoneType' object has no attribute 'endswith'

thanks for helping

**Comment by haoyangz** [comment]
I assume you did the following to prepare the toy data:
```
cd $REPO_HOME
for dtype in 'train' 'valid' 'test'
do
	paste - - -d' ' < example/$dtype.fa > tmp.tsv
	python embedH5.py tmp.tsv example/$dtype.target expt1/trial2.$dtype.h5
done
```

This generates data under a folder called "expt1" and all the files are prefixed with "trial2". Therefore `DATA_TOPDIR`  should be "expt1" and `DATA_CODE` should be "trial2".

To run the toy example, you can use the example model code at "example/model.py". Thus `MODEL_TOPDIR` should be "example" and `MODEL_FILE_NAME` should be "model.py".

Putting them together, you should run 

```
python main.py -d expt1 -c trial2 -m example/model.py -s 101 -y -t -e
```

**Comment by shay86** [comment]
thanks it run
   python main.py -d expt1 -c trial2 -m example/model.py -s 101 -hi 9 -te 20
   Using Theano backend.

but this is what it gave me just  create an empty [Model folder] in expt1 folder . I think there is some thing wrong because the model did not start training the data.
Thank you for your time but i hope you help me understand where the code will put the predicted file and give me the accuracy of 86%

**Comment by haoyangz** [comment]
You didn't give it an order (`-y` for hyper-param tuning, `-t` for training, and `-e` for testing). In the [README](https://github.com/gifford-lab/Keras-genomics), the bracket `[]` meant the options in the bracket are optional. So you should run with `-y -hi 9 -t -te 20`.

**Comment by shay86** [comment]
I don't know what is going wrong i run every thing as it should be. This time i get this ...sorry:


      python main.py -d expt1 -c trial2 -m example/model.py -s 101 -y -hi 9 -t -te 20 -bs 100 -e
      Using Theano backend.
      /home/shayan/.local/lib/python2.7/site-packages/hyperas/optim.pyhow run a python program in     keras theano environmentis 
     /home/shayan/.local/lib/python2.7/site-packages/hyperas/optim.py
     /home/shayan/.local/lib/python2.7/site-packages/hyperas/optim.py
     main.py
     Traceback (most recent call last):
      File "main.py", line 81, in <module>
      best_run, best_model optim.minimize(model=mymodel.model,data=mymodel.data,algo=tpe.suggest,max_evals=int(args.hype riter),trials=Trials())
     File "/home/shayan/.local/lib/python2.7/site-packages/hyperas/optim.py", line 42, in minimize
     notebook_name=notebook_name, verbose=verbose)
     File "/home/shayan/.local/lib/python2.7/site-packages/hyperas/optim.py", line 62, in base_minimizer
     model_str = get_hyperopt_model_string(model, data, notebook_name, verbose, stack)
     File "/home/shayan/.local/lib/python2.7/site-packages/hyperas/optim.py", line 132, in   get_hyperopt_model_string
      imports = extract_imports(cleaned_source, verbose)
      File "/home/shayan/.local/lib/python2.7/site-packages/hyperas/utils.py", line 31, in extract_imports
      tree = ast.parse(source)
      File "/usr/lib/python2.7/ast.py", line 37, in parse
      return compile(source, filename, mode, PyCF_ONLY_AST)
      File "<unknown>", line 81
      best_archit,best_optim,best_lossfunc = best_model
                                                    ^
      IndentationError: unindent does not match any outer indentation level

**Comment by haoyangz** [comment]
You seem to have changed the indent of "best_archit,best_optim,best_lossfunc = best_model" this line in `main.py`. Try matching the indent level. The original `main.py` uses space rather than tab. If you are not familar with Python and can't fix it, try redownloading `main.py`.

**Comment by shay86** [comment]
hi,
I download pyCharm to run the project and get over the above error but I get this new error that i can not over come.Even I am sure it is not space or tab problem because I try this trick several times.Moveover pyCharm tell you about these problems 
[
![screenshot from 2017-04-25 11-59-33](https://cloud.githubusercontent.com/assets/27968351/25397836/602fbb7a-29af-11e7-9c14-e029c1746e02.png)
](url)

**Comment by shay86** [comment]
hi,
I download PyCharm to run the project but I get this error which is not space or tab error because I try this trick and it did not work.Moreover PyCharm tell you about this link of error 
![screenshot from 2017-04-25 11-59-33](https://cloud.githubusercontent.com/assets/27968351/25397957/d6b89aaa-29af-11e7-80f4-6ac186dfa96e.png)

**Comment by haoyangz** [comment]
If you use the original `main.py` without touching anything, you should be able to run it without any problem. From the error message, it seems to indicate again something is wrong with your indent in line "model.load_weight(weight_file)".

**Comment by shay86** [comment]
I manage fixing the error by deleting all spaces in the main.py program and put it back again and do the same for model.py 
thanks a lot for helping
