### ISSUE TITLE
An error about Keras: Received unknown keyword arguments: {'validation_steps': 10.0}

### ISSUE THREAD

**Issue by YYingXia** [gifford-lab/Keras-genomics#3]
Hi,haoyang,
I am trying to run this code，when it is running into this part:
 " history_callback = model.fit_generator(mymodel.BatchGenerator2(args.batchsize,trainbatch_num,'train',topdir,data_code)                    ,np.ceil(float(train_size)/args.batchsize),args.trainepoch,validation_data=mymodel.BatchGenerator2(args.batchsize,validbatch_num,'valid',topdir,data_code),nb_validation_steps=np.ceil(float(valid_size)/args.batchsize),callbacks = [checkpointer])"
an error occurred about Keras: Received unknown keyword arguments: {'validation_steps': 10.0}.
Does it relevant to the version of keras?
What's the version of keras you used?
Thank you!

**Comment by haoyangz** [comment]
Yes I used Keras 1.2. Feel free to change it to the new interface ("validation_data") if you are not using Docker.
